### ISSUE TITLE
There does not appear to be a data source for network profiles

### ISSUE THREAD

**Issue by chrisd27519** [vmware/terraform-provider-vra#83]
There does not appear to be a data source for network profiles. Is there an alternate name in use to apply network profiles to a machine resource?

**Comment by dmettem** [comment]
A machine resource needs the network ids that you can get using the "vra_network" data source. Based on the network id provided in the machine resource and the constraints, the network profile is auto selected.
Please refer to the [example](https://github.com/vmware/terraform-provider-vra/blob/master/examples/machine/main.tf) or the [documentation](https://github.com/vmware/terraform-provider-vra/blob/master/website/docs/r/machine.html.markdown).

**Comment by chrisd27519** [comment]
Ok, so the use model you are specifying (relative to vCenter OnPrem) is the user must identify the vCenter portgroup by name to attach the machine to, and constraint tags identify an existing network profile to use to allocate ip address, etc.

This is backwards from how vRA blueprints operate. Currently, I have the user specifying the network constraints (tag values) to identify a specific network profile, and the network profile identifies the vCenter portgroup to attach to. 

In your case, The user must know information that they do not know when using Blueprints in vRA.
In terraform there has to be a way to identify a network profile and the information within it defines the vra_network.

**Comment by dmettem** [comment]
Thanks for explaining the use-case. I'm working on the data source for network profiles that should give information about the networks and tags so that user can specify the network constraints while requesting a machine resource. Will that help?

**Comment by chrisd27519** [comment]
Absolutely. In my use case the user only knows the constraints (tag values), not the underlying infrastructure, as is the case with image mapping. In this way we can limit the networks they are allowed to use by project. If we allow use of explicit portgroups they would have the ability to attach to a network they are in fact "not allowed" to connect to.

**Comment by mdittbrenner215** [comment]
is there an ETA on this?

**Comment by dmettem** [comment]
I'll try to get a PR out for this today.

**Comment by dmettem** [comment]
Fixed via #92 
Please note that some of the existing arguments in vra_network_profile are renamed for consistency.

**Comment by markpeek** [comment]
@mdittbrenner215 this has been released [here](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.2).

**Comment by mdittbrenner215** [comment]
@markpeek thanks i had saw and just built it locally too.

**Comment by mdittbrenner215** [comment]
It looks like this doesnt fix the issue.  We can not get an IP address from vra IPAM from a machine resource.
